-- Anthony Ly, Harpreet Sangha, Volodymyr Ivanov --
-- Assignment 16 --

-- Dropping tables
DROP TABLE IF EXISTS SALE;
DROP TABLE IF EXISTS PURCHASE;
DROP TABLE IF EXISTS WITHDRAWAL;
DROP TABLE IF EXISTS DEPOSIT;
DROP TABLE IF EXISTS DIVIDEND;
DROP TABLE IF EXISTS INVESTMENT;
DROP TABLE IF EXISTS TRANSACTIONS;
DROP TABLE IF EXISTS ACCOUNTS;
DROP TABLE IF EXISTS BROKERAGE;

-- Creating tables
CREATE TABLE BROKERAGE (
    BROK_ID     CHAR(5) PRIMARY KEY,
    PAYOR_ID    CHAR(5) NOT NULL,
    BROK_NAME   VARCHAR(20) NOT NULL,
    BROK_ADDR   VARCHAR(20) NOT NULL
);

CREATE TABLE ACCOUNTS (
    ACC_ID      CHAR(5) PRIMARY KEY,
    TAXABLE     BOOLEAN NOT NULL,
    ACC_TYPE    VARCHAR(10) NOT NULL,
    BALANCE     DECIMAL(13,4) NOT NULL,
    PAYOR_ID    CHAR(5) NOT NULL,
    BROK_ID     CHAR(5) NOT NULL,
    FOREIGN KEY(BROK_ID) REFERENCES BROKERAGE(BROK_ID)
);

CREATE TABLE TRANSACTIONS (
    TRAN_ID     CHAR(5) PRIMARY KEY,
    TRAN_DATE   DATE NOT NULL,
    DESCRP      VARCHAR(256),
    AMOUNT      DECIMAL(13,4) NOT NULL,
    ACC_ID      CHAR(5) NOT NULL,
    TRAN_TYPE   VARCHAR(2) NOT NULL,
    TRAN_INFO   CHAR(5) NOT NULL,
    FOREIGN KEY(ACC_ID) REFERENCES ACCOUNTS(ACC_ID)
);

CREATE TABLE INVESTMENT (
    INV_ID      CHAR(5) PRIMARY KEY,
    TICKER      VARCHAR(4) NOT NULL,
    INV_DATE    DATE NOT NULL,
    SHARE_QTY   DECIMAL(13,4) NOT NULL,
    CATEGORY    VARCHAR(256) NOT NULL,
    ACC_ID      CHAR(5) NOT NULL,
    FOREIGN KEY(ACC_ID) REFERENCES ACCOUNTS(ACC_ID)
);

CREATE TABLE DIVIDEND (
    DIV_ID      CHAR(5) PRIMARY KEY, 
    SHARE_QTY   DECIMAL(13,4) NOT NULL,
    PRICE_PER   DECIMAL(13,4) NOT NULL,
    INV_ID      CHAR(5) NOT NULL,
    TRAN_ID     CHAR(5) NOT NULL,
    FOREIGN KEY(INV_ID) REFERENCES INVESTMENT(INV_ID),
    FOREIGN KEY(TRAN_ID) REFERENCES TRANSACTIONS(TRAN_ID)
);

CREATE TABLE DEPOSIT (
    TRAN_ID     CHAR(5) PRIMARY KEY,
    ACC_ID      CHAR(5) NOT NULL,
    FOREIGN KEY(TRAN_ID) REFERENCES TRANSACTIONS(TRAN_ID),
    FOREIGN KEY(ACC_ID) REFERENCES TRANSACTIONS(ACC_ID)
);

CREATE TABLE WITHDRAWAL (
    TRAN_ID     CHAR(5) PRIMARY KEY,
    ACC_ID      CHAR(5) NOT NULL,
    FOREIGN KEY(TRAN_ID) REFERENCES TRANSACTIONS(TRAN_ID),
    FOREIGN KEY(ACC_ID) REFERENCES TRANSACTIONS(ACC_ID)
);

CREATE TABLE PURCHASE (
    TRAN_ID     CHAR(5) PRIMARY KEY,
    SELLER_ID   CHAR(5) NOT NULL,
    SHARE_QTY   DECIMAL(13,4) NOT NULL,
    PRICE_PER   DECIMAL(13,4) NOT NULL,
    BUY_DATE  DATE NOT NULL,
    ACC_ID      CHAR(5) NOT NULL,
    FOREIGN KEY(TRAN_ID) REFERENCES TRANSACTIONS(TRAN_ID),
    FOREIGN KEY(ACC_ID) REFERENCES TRANSACTIONS(ACC_ID)
);

CREATE TABLE SALE (
    TRAN_ID     CHAR(5) PRIMARY KEY,
    BUYER_ID    CHAR(5) NOT NULL,
    SHARE_QTY   DECIMAL(13,4) NOT NULL,
    PRICE_PER   DECIMAL(13,4) NOT NULL,
    SALE_DATE   DATE NOT NULL,
    ACC_ID      CHAR(5) NOT NULL,
    FOREIGN KEY(TRAN_ID) REFERENCES TRANSACTIONS(TRAN_ID),
    FOREIGN KEY(ACC_ID) REFERENCES TRANSACTIONS(ACC_ID)
);
